apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: busybox
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          ports:
            - containerPort: 80
              name: busybox
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
