apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      volumes:
        - name: configmap-volume
          configMap:
            name: demo-configmap
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: pvc-dynamic
      containers:
        - name: demo
          image: devopsjourney1/mywebapp:latest
          envFrom:
            - secretRef:
                name: demo-secret
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "16Mi"
              cpu: 500m
          volumeMounts:
            - name: configmap-volume
              mountPath: /data/message.txt
              subPath: message.txt
            - name: pvc-volume
              mountPath: "/data"
